HospitalApp/Controllers/AppointmentController.cs
using HospitalApp.Core.Application.Interfaces.Services;
using HospitalApp.Core.Application.ViewModels.Appointment;
using HospitalApp.Core.Domain.Entities;
using HospitalApp.Middlewares;
using Microsoft.AspNetCore.Mvc;

namespace HospitalApp.Controllers
{
    public class AppointmentController : Controller
    {
        private readonly IAppointmentService _service;
        private readonly IPatientSevice _servicePatient;
        private readonly IDoctorService _serviceDr;
        private readonly ILabResultService _serviceResult;
        private readonly ValidateUserSession _validateUserSession;

        public AppointmentController(IAppointmentService service, IPatientSevice servicePatient, IDoctorService serviceDr, ValidateUserSession validateUserSession, ILabResultService serviceResult)
        {
            _service = service;
            _servicePatient = servicePatient;
            _serviceDr = serviceDr;
            _serviceResult = serviceResult;
            _validateUserSession = validateUserSession;
        }

        public async Task<IActionResult> Index()
        {
            if (!_validateUserSession.HasUser() || _validateUserSession.GetUserRole() != UserRole.Asistente)
            {
                return RedirectToRoute(new { controller = "User", action = "Permission"});
            }

            var list = await _service.GetAllViewModel();

            foreach (var appointment in list)
            {
                appointment.LabResultId = await _serviceResult.GetLabResultIdForAppointment(appointment.AppointmentId);
            }
            return View(list);
        }

        public async Task<IActionResult> Create()
        {
            if (!_validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            var patients = await _servicePatient.GetAllViewModel();
            var doctors = await _serviceDr.GetAllViewModel();
            var AppointmentViewModel = new SaveAppointmentViewModel
            {
                Patients = patients,
                Doctors = doctors
            };
            return View("SaveAppointment", AppointmentViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Create(SaveAppointmentViewModel newAppointment)
        {
            if (!_validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            if (!ModelState.IsValid)
            {
                newAppointment.Patients = await _servicePatient.GetAllViewModel();
                newAppointment.Doctors = await _serviceDr.GetAllViewModel();
                return View("SaveAppointment", newAppointment);
            }

            await _service.Add(newAppointment);
            return RedirectToRoute(new { controller = "Appointment", action = "Index" });
        }

        public async Task<IActionResult> Edit(int id)
        {
            if (!_validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            var appointmentViewModel = await _service.GetByIdSaveViewModel(id);
            appointmentViewModel.Patients = await _servicePatient.GetAllViewModel();
            appointmentViewModel.Doctors = await _serviceDr.GetAllViewModel();
            return View("SaveAppointment", appointmentViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(SaveAppointmentViewModel updatedAppointmentViewModel)
        {
            if (!_validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            if (!ModelState.IsValid)
            {
                updatedAppointmentViewModel.Patients = await _servicePatient.GetAllViewModel();
                updatedAppointmentViewModel.Doctors = await _serviceDr.GetAllViewModel();
                return View("SaveAppointment", updatedAppointmentViewModel);
            }

            await _service.Update(updatedAppointmentViewModel);
            return RedirectToRoute(new { controller = "Appointment", action = "Index" });
        }

        public async Task<IActionResult> Delete(int id)
        {
            if (!_validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            var appointmentViewModel =  await _service.GetByIdSaveViewModel(id);

            var patient = await _servicePatient.GetByIdSaveViewModel(appointmentViewModel.PatientId);
            var doctor = await _serviceDr.GetByIdSaveViewModel(appointmentViewModel.DoctorId);

            var deleteAppointmentViewModel = new DeleteAppointmentViewModel
            {
                Id = appointmentViewModel.Id,
                PatientName = $"{patient.FirstName} {patient.LastName}",
                DoctorName = $"{doctor.FirstName} {doctor.LastName}"
            };

            return View(deleteAppointmentViewModel); 
        }

        [HttpPost]
        public async Task<IActionResult> DeletePost(int id)
        {
            if (! _validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            await _service.Delete(id);
            return RedirectToRoute(new { controller = "Appointment", action = "Index" });
        }

        public async Task<IActionResult> CompleteAppointment(int appointmentId)
        {
            if (! _validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            if (ModelState.IsValid)
            {
                await _service.ChangeAppointmentStatusAsync(appointmentId, AppointmentStatus.Completada);
                return RedirectToAction("Index");
            }
            return RedirectToRoute(new { controller = "Appointment", action = "Index" });
        }


    }
}

HospitalApp/Controllers/LabResultController.cs
using HospitalApp.Core.Application.Interfaces.Services;
using HospitalApp.Core.Application.ViewModels.LabResult;
using HospitalApp.Core.Domain.Entities;
using HospitalApp.Middlewares;
using Microsoft.AspNetCore.Mvc;

namespace HospitalApp.Controllers
{
    public class LabResultController : Controller
    {
        private readonly ILabResultService _service;
        private readonly ValidateUserSession _validateUserSession;

        public LabResultController(ILabResultService service, ValidateUserSession validateUserSession)
        {
            _service = service;
            _validateUserSession = validateUserSession;
        }

        public async Task<IActionResult> Index(string? cedula, int? appointmentId)
        {
            if (!_validateUserSession.HasUser() || _validateUserSession.GetUserRole() != UserRole.Asistente)
            {
                return RedirectToRoute(new { controller = "User", action = "Permission" });
            }

            if (!_validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            if (cedula == null)
            {
                var list = await _service.GetAllViewModel();
                return View(list);

            } else
            {
                var filtered = await _service.GetAllViewModelFiltered(cedula);
                ViewBag.theAppointment = appointmentId;
                return View(filtered);
            }
        }

        public async Task<IActionResult> Consult(int? labResultId = null, int? appointmentId = null)
        {
            if (!_validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            if (appointmentId.HasValue)
            {
                var labResults = await _service.GetLabResultsByAppointmentId(appointmentId.Value);
                return View("AppointmentLabResult", labResults);
            }
            else if (labResultId.HasValue)
            {
                var labResult = await _service.GetByIdSaveViewModel(labResultId.Value);
                var labResultsViewModelList = new List<SaveLabResultViewModel> { labResult };
                return RedirectToAction("AppointmentLabResult", labResultsViewModelList);
            }
            else
            {
                var labResults = await _service.GetAllViewModel();

                var labResultsViewModel = labResults.Select(result => new SaveLabResultViewModel
                {
                    AppointmentId = result.AppointmentId,
                    PatientName = result.PatientName,
                    LabTestName = result.LabTestName,
                    Status = result.Status,
                }).ToList();

                return View("AppointmentLabResult", labResultsViewModel);
            }
        }


        public async Task<IActionResult> Create()
        {
            if (!_validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            return View("SaveLabResult", new SaveLabResultViewModel());
        }

        public async Task<IActionResult> Report(int id, int appointmentId)
        {
            if (!_validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            var resultViewModel = await _service.GetByIdSaveViewModel(id);
            return View("SaveLabResult", resultViewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Report(SaveLabResultViewModel updatedResultViewModel)
        {
            if (!_validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            if (!ModelState.IsValid)
            {
                return View("SaveLabResult", updatedResultViewModel);
            }

            await _service.Update(updatedResultViewModel);
            await _service.ChangeLabResultStatusAsync(updatedResultViewModel.Id, LabResultStatus.Completado);

            var all = await _service.GetAllViewModel();

            return View("Index", all);
        }


        public async Task<IActionResult> FinalResults(int appointmentId, string labResultIds)
        {
            if (!_validateUserSession.HasUser())
            {
                return RedirectToRoute(new { controller = "User", action = "Index" });
            }

            var labResultIdsList = !string.IsNullOrEmpty(labResultIds) ? labResultIds.Split(',').Select(int.Parse).ToList() : new List<int>();
            var labResults = await _service.GetLabResultsByAppointmentId(appointmentId);

            var completedResults = await _service.GetCompletedAsync(appointmentId);

            var labResultsViewModel = completedResults.Select(result => new LabResultViewModel
            {
                ResultadoDigitado = result.ResultadoDigitado,
                LabTestName = result.LabTestName,
                PatientName = result.PatientName,
                AppointmentId = result.AppointmentId,
                Status = result.Status
            }).ToList();

            return View("CompletedLabResult", labResultsViewModel);
        }

    }
}

HospitalApp/Views/Appointment/Delete.cshtml
@model HospitalApp.Core.Application.ViewModels.Appointment.DeleteAppointmentViewModel

@{
    ViewData["Title"] = "Eliminar Cita";
}

<div class="container h-100">
    <div class="row justify-content-center" style="min-height: 100vh;">
        <div class="col-8 text-center mt-4">
            <h6 class="mb-4 mt-4">
                ¿Está seguro(a) que desea eliminar la cita del paciente
                "@($"{@Model.PatientName}")"
                con el/la doctor(a) "@($"{@Model.DoctorName}")"?
            </h6>
            <hr />
            <form class="text-right" method="post" asp-controller="Appointment" asp-action="DeletePost">
                <button class="btn btn-outline-danger btn-sm me-2" type="submit">Eliminar</button>
                <a class="btn btn-outline-secondary btn-sm" asp-controller="Appointment" asp-action="Index">Cancelar</a>
                <input type="hidden" asp-for="Id">
            </form>
        </div>
    </div>
</div>

HospitalApp/Views/Appointment/Index.cshtml
@model List<HospitalApp.Core.Application.ViewModels.AppointmentViewModel>

@using HospitalApp.Core.Domain.Entities

@{
    ViewData["Title"] = "Appointments";
}

<div class="container mt-5">
    <h3 class="text-center mb-4">Citas</h3>
    <hr />

    <div class="row justify-content-center">
        <div class="col">
            <div class="d-flex justify-content-end mb-3">
                <a asp-controller="Appointment" asp-action="Create" class="btn btn-sm btn-dark">
                    Nueva <i class="fas fa-plus"></i>
                </a>
            </div>
            @if (Model == null || !Model.Any())
            {
                <div class="alert alert-danger" role="alert">
                    No se encontraron citas.
                </div>
            }
            else
            {
                <table class="table table-success table-striped mt-3">
                    <thead>
                        <tr>
                            <th>Paciente</th>
                            <th>Doctor</th>
                            <th>Fecha</th>
                            <th>Hora</th>
                            <th>Razón</th>
                            <th>Estado</th>
                            <th class="text-end">Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>@item.PatientName</td>
                                <td>@item.DoctorName</td>
                                <td>@item.Date</td>
                                <td>@item.Time</td>
                                <td>@item.Reason</td>
                                <td>@item.Status</td>
                                <td class="text-end">
                                    @if (item.Status == AppointmentStatus.Consulta_Pendiente)
                                    {
                                        <a class="btn btn-warning btn-sm me-1" asp-controller="LabTest" asp-action="SelectLabTests" asp-route-AppointmentId="@item.AppointmentId">
                                            Consultar
                                        </a>
                                    }
                                    else if (item.Status == AppointmentStatus.Pendiente_Resultados)
                                    {
                                        <a class="btn btn-info btn-sm me-1" asp-controller="LabResult" asp-action="Consult" asp-route-LabResultId="@item.LabResultId" asp-route-AppointmentId="@item.AppointmentId">
                                            Consultar Resultados
                                        </a>
                                    }
                                    else if (item.Status == AppointmentStatus.Completada)
                                    {
                                        <a class="btn btn-success btn-sm me-1" asp-controller="LabResult" asp-action="FinalResults"
                                           asp-route-AppointmentId="@item.AppointmentId"  asp-route-LabResultIds="@string.Join(",", item.LabResultIds ?? new List<int>())">
                                            Ver resultados
                                        </a>

                                    }
                                    <a class="me-3" asp-controller="Appointment" asp-action="Edit" asp-route-id="@item.AppointmentId">
                                        <i class="fas fa-edit text-black"></i>
                                    </a>
                                    <a asp-controller="Appointment" asp-action="Delete" asp-route-id="@item.AppointmentId">
                                        <i class="fas fa-trash text-black"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>
</div>

HospitalApp/Views/Appointment/SaveAppointment.cshtml
@model HospitalApp.Core.Application.ViewModels.Appointment.SaveAppointmentViewModel
@using HospitalApp.Core.Domain.Entities

@{
    bool editMode = Model.Id == 0 ? false : true;

    ViewData["Title"] = editMode == false ? "Crear cita" : "Editar cita";
}

@{
    var enumType = typeof(AppointmentStatus);
    var enumValues = Enum.GetValues(enumType).Cast<AppointmentStatus>();
}


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-7">
            <div class="card p-3 bg-success bg-opacity-10 mb-5">
                <div class="card-header bg-opacity-50 bg-success">
                    <h3 class="text-center">@ViewData["Title"]</h3>
                </div>
                <div class="card-body">
                    <form asp-controller="Appointment" asp-action="@(editMode? "Edit": "Create")" method="post">
                        <div class="mb-3">
                            <label asp-for="PatientId" class="form-label">Nombre del paciente</label>
                            <select asp-for="PatientId" class="form-select">
                                <option value="0">Seleccione</option>
                                @foreach (var patient in Model.Patients)
                                {
                                    <option value="@patient.Id">@($"{patient.FirstName} {patient.LastName}")</option>
                                }
                            </select>
                            <span asp-validation-for="PatientId" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="DoctorId" class="form-label">Nombre del doctor</label>
                            <select asp-for="DoctorId" class="form-select">
                                <option value="0">Seleccione</option>
                                @foreach (var doctor in Model.Doctors)
                                {
                                    <option value="@doctor.Id">@($"{doctor.FirstName} {doctor.LastName}")</option>
                                }
                            </select>
                            <span asp-validation-for="DoctorId" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Date" class="form-label">Fecha de la cita</label>
                            <input asp-for="Date" type="date" class="form-control" min="@DateTime.Today.ToString("yyyy-MM-dd")"
                                   value="@Model.Date.ToDateTime(new TimeOnly()).ToString("yyyy-MM-dd")">
                            <span asp-validation-for="Date" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Time" class="form-label">Hora</label>
                            <input asp-for="Time" type="time" min="" max="" class="form-control">
                            <span asp-validation-for="Time" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Reason" class="form-label">Razón</label>
                            <input asp-for="Reason" class="form-control" placeholder="Ingrese la causa de la cita">
                            <span asp-validation-for="Reason" class="text-danger"></span>
                        </div>
                        <div class="mb-3">
                            <label asp-for="Status" class="form-label">Estatus</label>
                            <select disabled asp-for="Status" class="form-select">
                                <option value="0" selected>@Model.Status</option>
                            </select>
                            <span asp-validation-for="Status" class="text-danger"></span>
                        </div>

                        <input type="hidden" asp-for="Id">
                        <button type="submit" class="btn btn-success">Guardar</button>
                        <a asp-controller="Appointment" asp-action="Index" class="btn btn-secondary">Volver atrás</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

HospitalApp/Views/Appointment/SelectLabTests.cshtml
@model HospitalApp.Core.Application.ViewModels.LabTest.SelectLabTestsViewModel

@{
    ViewData["Title"] = "Selección de pruebas";
}

<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-7">
            <div class="card p-3 bg-success bg-opacity-10 mb-5">
                <div class="card-header bg-opacity-50 bg-success">
                    <h3 class="text-center">@ViewData["Title"]</h3>
                </div>
                <div class="card-body">
                    <form asp-controller="Appointment" asp-action="PerformLabTests" method="post">
                        <input type="hidden" asp-for="AppointmentId" value="@Model.AppointmentId"/>
                        <p>@Model.AppointmentId</p>

                        @for (int i = 0; i < Model.AvailableLabTests.Count; i++)
                        {
                            <div class="form-check">
                                <input asp-for="@Model.AvailableLabTests[i].IsSelected" class="form-check-input" />
                                <label asp-for="@Model.AvailableLabTests[i].IsSelected" class="form-check-label">@Model.AvailableLabTests[i].Name</label>
                                <input type="hidden" asp-for="@Model.AvailableLabTests[i].LabTestId" />
                                <input type="hidden" asp-for="@Model.AvailableLabTests[i].Name" />
                            </div>
                        }
                        <button type="submit" class="btn btn-success">Realizar pruebas</button>
                        <a asp-controller="Appointment" asp-action="Index" class="btn btn-secondary">Volver atrás</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>